name: Lab 6 - Parse Employee JSON

on:
  workflow_dispatch:
    inputs:
      json_input:
        description: "Enter employee JSON data"
        required: true
        default: '{"id": 101, "name": "Sara", "department": "IT", "isManager": true}'

jobs:
  parse_json:
    runs-on: ubuntu-latest
    steps:
      - name: Show Raw Input
        run: echo "Input JSON: ${{ github.event.inputs.json_input }}"

      - name: Use jq to Parse JSON
        run: |
          DATA=$(echo '${{ github.event.inputs.json_input }}' | jq -c '.')
          echo "Parsed ID: $(echo "$DATA" | jq -r '.id')"
          echo "Parsed Name: $(echo "$DATA" | jq -r '.name')"
          echo "Parsed Department: $(echo "$DATA" | jq -r '.department')"
          echo "Is Manager?: $(echo "$DATA" | jq -r '.isManager')"
