name: Lab 6 - JSON Input

on:
  workflow_dispatch:
    inputs:
      json_input:
        description: 'JSON input'
        required: true
        default: '{"name": "Alice", "age": 25}'

jobs:
  parse_json:
    runs-on: ubuntu-latest
    steps:
      - name: Parse JSON Input
        id: parse
        run: |
          echo '${{ toJSON(github.event.inputs.json_input) }}' > raw.json
          echo "::set-output name=data::$(echo '${{ github.event.inputs.json_input }}' | jq '.')"

      - name: Use fromJSON
        run: |
          DATA=$(echo '${{ github.event.inputs.json_input }}' | jq -c '.')
          echo "Parsed name: $(echo "$DATA" | jq -r '.name')"
          echo "Parsed age: $(echo "$DATA" | jq -r '.age')"
