name: Print All GitHub Contexts

on: [push, workflow_dispatch] 

jobs:
  print-contexts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print github context
        run: echo '${{ toJson(github) }}'

      - name: Print env context
        run: echo '${{ toJson(env) }}'

      - name: Print vars context
        run: echo '${{ toJson(vars) }}'

      - name: Print job context
        run: echo '${{ toJson(job) }}'

      - name: Print runner context
        run: echo '${{ toJson(runner) }}'

      - name: Print matrix context
        run: echo '${{ toJson(matrix) }}'

      - name: Print strategy context
        run: echo '${{ toJson(strategy) }}'

      - name: Print steps context
        run: echo '${{ toJson(steps) }}'

      - name: Print needs context
        run: echo '${{ toJson(needs) }}'

      - name: Print inputs context
        run: echo '${{ toJson(inputs) }}'

      - name: Print secrets context
        run: |
          echo "Secrets cannot be printed for security reasons."
